version: "3"

services:
  mysql-db:
    # DB 서비스
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pomodotory
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - gyumpark-network

  react-app:
    # 프론트 서비스
    image: gyumpark/pomodotory-react-app:latest
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/var/front
    networks:
      - gyumpark-network

  nestjs-app:
    # 백엔드 서비스
    image: gyumpark/pomodotory-nestjs-app:latest
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back:/var/back
    networks:
      - gyumpark-network
    depends_on:
      - mysql-db

volumes:
  mysql:

networks:
  gyumpark-network:
    driver: bridge
